# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiUtem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MiUtem

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'

  target 'MiUtem-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiUtemTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
